blank_issues_enabled: false
contact_links:
  - name: ⚠️ Application issue
    url: https://github.com/tsundoku-otaku/tsundoku/issues/
    about: Issues and requests about the app itself should be opened in Tsundoku's repository instead
  - name: 📦 Extension list
    url: https://novelsourcery.github.io/extensions
    about: List of all available extensions with download links
  - name: 🖥️ Tsundoku website
    url: https://tsundoku-otaku.github.io/docs/guides/troubleshooting/
    about: Guides, troubleshooting, and answers to common questions
